project:
  type: website
  resources:
    - js/

website:
  title: "til"
  site-url: https://lawwu.github.io/til/
  description: "Lawrence Wu's Today I Learned"
  google-analytics: "G-LN4GM4FVCJ"
  cookie-consent: true  
  navbar:
    right:
      - icon: github
        href: https://github.com/lawwu/til
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <script>
            // Log script loading attempt
            console.log('Attempting to load GitHub stars script');
            
            // Determine the correct path for the script
            let baseUrl = '';
            if (window.location.hostname === 'localhost') {
              baseUrl = '/';
            } else {
              baseUrl = '/til/';
            }
            
            // Create script tag
            const scriptTag = document.createElement('script');
            scriptTag.src = baseUrl + 'js/github-stars.js';
            scriptTag.async = false;
            scriptTag.defer = true;
            scriptTag.onload = () => console.log('GitHub stars script loaded successfully');
            scriptTag.onerror = (err) => console.error('Error loading GitHub stars script:', err);
            
            // Append to document head
            document.head.appendChild(scriptTag);
            console.log('Script tag created with src:', scriptTag.src);
          </script>

execute:
  freeze: auto

