project:
  type: website

website:
  title: "til"
  site-url: https://lawwu.github.io/til/
  description: "Lawrence Wu's Today I Learned"
  google-analytics: "G-LN4GM4FVCJ"
  cookie-consent: true  
  navbar:
    right:
      - icon: github
        href: https://github.com/lawwu/til
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <script>
            // Use relative path that works in both local and production
            document.write('<script src="' + 
                          (window.location.hostname === 'localhost' ? '/' : '/til/') + 
                          'github-stars.js"><\/script>');
          </script>

execute:
  freeze: auto

